# Site settings
title: Trevor Long
name: Trevor Long

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: Portfolio
   url: https://trevorlong.myportfolio.com/
 - title: GitHub
   url: https://github.com/DroTron
 - title: Thingiverse
   url: https://www.thingiverse.com/drotron/designs
 - title: LinkedIn
   url: https://www.linkedin.com/in/trevorlong/


#Any buzzword skills you want to include
skills:
 - Matlab
 - Python
 - AWS/Vultr
 - Solidworks/Fusion 360
 - Microsoft Office
 - Manual and CNC lathe and mill
 - Linux/BASH
 - Advanced PC building and troubleshooting
 - Writing skills
 - Photography/Videography
 - Adobe Photoshop, Lightroom, Premiere, and Audition
 - Abaqus CAE
 - ANSYS Fluent
 - Leadership
 - Organization


#Work experience is required
roles:
 - title: Advanced Repair Agent
   start: May 2019
   end: Ongoing
   employer: Geek Squad
   description: As an Advanced Repair Agent, it was my responsibility to fix Windows computers, Macs, and iPhones. This job also required me to maintain my status as a Apple Certified iOS Technician.
 - title: Apple Pro
   start: January 2018
   end: May 2019
   employer: Best Buy
   description: As an Apple Pro, I attended monthly Apple trainings, and I trained other employees on how to use and demo Apple products. As Apple Pro, I was the top performer in the store twice, including an award for store MVP June of 2018, and the Expert Service award March of 2018.
 - title: Sales Consultant
   start: May 2017
   end: January 2018
   employer: Best Buy
   description: As a sales consultant, I helped customers and answered questions about computers and cameras. This role also included meeting sales goals and down-stocking and cleaning the store.

#Education is required
education:
 - level: Bachelor of Science (B.Sc.)
   date: 2022
   subject: Mechanical Engineering, Concentration in Aerospace Engineering
   school: Colorado State University



#List of interesting Github repo/projects to include - optional
github:
 - DroTron/Robo-Rick
 - DroTron/Numerical-Methods
 - DroTron/Mechatronics-Arduino-Code
 - DroTron/bot-rick
 - DroTron/Trevors-Cleanup-Script
 - DroTron/Submarine-Project
 - DroTron/Nerf-Disrupter-Replica
intro: |
  I am a student at CSU currently studying mechanical engineering with a concentration in aerospace engineering.
  I am most proud of being a two time Science Olympiad National medalist and an Eagle Scout.
  Outside of school I am interested in Photography, Videography, and learning Python to program my Discord bot, Robo Rick.
  I look forward to meeting you soon!

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
   <strong>Python</strong>: I mainly use Python to develop my Discord bot, <a target="_blank" href="https://github.com/DroTron/Robo-Rick">"Robo Rick"</a>. Robo Rick is currently deployed on AWS and is fully functional running on multiple servers.
   <strong>Cloud platforms</strong>: I currently run Robo Rick on an AWS EC2 instance, I also have experience running Robo Rick on Vultr's "Cloud Compute" instance.
