# Site settings
title: Akash TP 
twitter_username: _akash_tp
name: Akash TP

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: Twitter
   url: https://twitter.com/_akash_tp
 - title: GitHub
   url: https://github.com/Akashtp
 - title: LinkedIn
   url: https://www.linkedin.com/pub/rob-hinds/21/361/3b1

#Any buzzword skills you want to include
skills:
 - Python 
 - OpenCV
 - .net
 - Product management
 - Java
 - SQL
 - Machine learning
 - Android Development
 
#Work experience is required
roles:
 - title: Freelance Software Developer
   start: 2020
   end: Ongoing
   employer: Self

 - title: Software Developer
   start: 2019
   end: 2020
   employer: Perfect Fit Systems Private Limited
   
 - title: Backend Developer
   start: 2018
   end: 2019
   employer: Predict.ai (Self Employed)
   
   
#Education is required
education:
 - level: Bachelor of Technology (B.Tech)
   date: 2019
   subject: Information Technology 
   school: Cochin University Of Science And Technologies.



intro: |
  I am a Software Engineer with 2 years experience working in technology. I have primarily worked on the Python, but have worked across a broad range of technologies thereon: Java,  Android and most recently .net. <br/><br/>
  I enjoy building interesting products, with a good Product Management focus and a good emphasis on good engineering principles and clean code.<br/><br/>
  
