# Site settings
title: Justin Davis
twitter_username: justindavis
name: Justin Davis

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: GitHub
   url: https://github.com/justin-davis-seiv
 - title: LinkedIn
   url: https://www.linkedin.com/in/justin-davis-3383211b2/
 

#Any buzzword skills you want to include
skills:
 - Business Analytics
 - SQL
 - Agile Methodologies
 - Project Management
 - Technology Opertaions
 - Confluence
 - JIRA
 - Java
 - SDLC
 - Market Research
 - JPA
 - Microsoft Suite
 - Marketing


#Blogfeed is optional - including this will add JS to call the feed and populate blog list
blogfeed: https://automateddeveloper.blogspot.com/feeds/posts/default?alt=json

#Work experience is required
roles:
  - title: Operations Analyst Intern
    start: May 2023
    end: August 2023
    employer: Walmart Global Tech
    location: Bentonville, AR
    description: |
      - Conducted real-time monitoring and analysis of dashboards for the Global Integrated Fulfillment system, reducing average time of resolution by 30%.
      - Developed recommendations for documentation standards through JIRA for the Command and Control Center (CCC), resulting in increased documentation across 4 different projects.
      - Onboarded Walmart GoLocal to the CCC, working with technical teams to integrate these applications into existing support systems.

  - title: Business Analyst Intern
    start: January 2023
    end: May 2023
    employer: American Fidelity Assurance
    location: Oklahoma City, OK
    description: |
      - Utilized Excel and JIRA to clarify, summarize, and document 150 technical business requirements.
      - Transferred and organized requirements from JIRA to TopTeam, maintaining thorough documentation of user interface fields.
      - Created training materials and documented best practices for project management tools, including TopTeam.

  - title: LMS Support Intern
    start: August 2022
    end: December 2022
    employer: Oklahoma Christian University
    location: Edmond, OK
    description: |
      - Communicated technical solutions for Blackboard, the university's Learning Management System.
      - Earned a positive helpdesk feedback rating of 97% through Zendesk.

  - title: Scrum Master Intern
    start: May 2022
    end: July 2022
    employer: Paycom
    location: Oklahoma City, OK
    description: |
      - Facilitated Scrum Ceremonies and monitored JIRA boards for two 9-member teams.
      - Restructured 90 company-wide Confluence pages to clarify training materials.
      - Analyzed 600 impediments using Excel and recommended resolution paths.
      - Assisted in implementing 4 new JIRA metrics for measuring Scrum team performance.
      - Awarded Scrum Master Intern MVP.

#Education is required
education:
 - level: Bachelor of Science (B.Sc.)
   date: 2020-2024
   subject: Computer Science with Business
   school: Oklahoma Christian University

#This section is optional (as is the image link below)
coursera:
   profileurl: https://www.coursera.org/user/i/c6362b4056f755a04bef6a791a62102b
   courses:
    - title: Functional Programming Principles in Scala
      link: https://www.coursera.org/course/progfun
      optionalimage: https://d1z850dzhxs7de.cloudfront.net/topics/progfun/small-icon.hover.png
      date: September 16, 2013
    - title: Algorithms Design and Analysis, Part 1
      link: https://www.coursera.org/specializations/algorithms
      optionalimage: https://d1z850dzhxs7de.cloudfront.net/topics/algo/small-icon.hover.png
      date: April 28, 2014



#List of interesting Github repo/projects to include - optional
github:
 - robhinds/robhinds.github.io
 - robhinds/ScaLambda
 - robhinds/opinionated-akka-http
 - robhinds/food2vec
 - robhinds/microservices
 - robhinds/spring-social-geeklist
 - robhinds/spring-social-stackoverflow
 - robhinds/genotype
 - robhinds/footweets
 - robhinds/ElasticSearchGradle


intro: |
  I am an aspiring business analyst with a solid foundation in computer science, currently pursuing my B.S. in Computer Science with Business at Oklahoma Christian University, with an expected graduation in April 2024. My education has equipped me with a strong grasp of various programming languages, data analysis, and project management methodologies. My hands-on experience during internships has further honed my skills in real-world settings, managing technical projects, optimizing operations, and delivering solutions in both startup and corporate environments. I have a keen interest in leveraging data to drive decision-making and optimize processes. <br/><br/>
  
  My passion for technology drives me to constantly explore and adopt new tools and frameworks to solve complex problems. I am always eager to collaborate with cross-functional teams to drive project success and contribute to organizational goals. My ability to communicate effectively and adapt to new challenges has been a cornerstone in my academic and professional journey. <br/><br/>
  
  I am actively seeking opportunities to further grow and apply my skills in business and data analysis roles, where I can contribute to building innovative solutions and improving operational efficiency. My ultimate goal is to continuously learn, contribute, and innovate in the rapidly evolving field of technology.

additionalinfo: |
   <strong>Java and SQL:</strong> Through my coursework and internships, I have developed proficiency in Java and SQL, which are crucial for backend development and data manipulation. My experience includes creating and optimizing queries, developing robust backend code, and understanding database structures. <br/><br/>
   <strong>Agile and Scrum:</strong> During my internship at Paycom, as a Scrum Master Intern, I facilitated Scrum ceremonies and monitored JIRA boards for two 9-member teams, which honed my understanding and practice of Agile and Scrum methodologies. I was awarded the Scrum Master Intern MVP for my contributions. <br/><br/>
   <strong>Data Analysis:</strong> My academic background and project experiences have equipped me with solid data analysis skills. I am proficient in using Microsoft Excel for data analysis and visualization, which was further sharpened during my internship at American Fidelity Assurance where I documented and gathered 150 business requirements. <br/><br/>
   <strong>Technical Documentation and Project Management:</strong> I have a knack for clear and thorough documentation, a skill that was pivotal in creating training materials and documentation standards for TopTeam and JIRA during my Business Analyst Intern role. <br/><br/>
   <strong>Learning Management Systems (LMS):</strong> At Oklahoma Christian University, I supported the Learning Management System (Blackboard) and resolved over 200 tickets, earning a positive helpdesk feedback rating of 97% through Zendesk. <br/><br/>
   <strong>Web Design:</strong> I have a foundational knowledge of web design with HTML and CSS, which allows me to understand and contribute to front-end development tasks. <br/><br/>
   <strong>Community Involvement:</strong> My leadership roles in various university clubs like Kappa Sigma Tau and Oklahoma Christian University American Marketing Association depict my ability to communicate, organize, and drive community engagement. I believe in active participation and giving back to the community, whether it's through organizing events or contributing to a shared goal. <br/><br/>
   <strong>Continuous Learning:</strong> I am committed to continuous learning and development. My active involvement in various projects, both academic and professional, reflect my eagerness to learn, adapt, and contribute to the evolving tech landscape. <br/><br/>
   <strong>Online Presence:</strong> Feel free to connect with me on [LinkedIn](https://www.linkedin.com/in/justin-davis10) or via email at davisjustin2024@gmail.com. I am always open to discussing new opportunities, sharing knowledge, or collaborating on exciting projects.
