# Site settings
title: Arjun B M
twitter_username: armatearjun
name: Arjun B M

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: Blog
   url: http://armatethetechmate.blogspot.com/
 - title: GitHub
   url: https://github.com/arjunbm13
 - title: StackOverflow
   url: https://stackoverflow.com/users/3282775/armate
 - title: DZone
   url: https://dzone.com
 - title: LinkedIn
   url: https://www.linkedin.com/in/armate/

#Any buzzword skills you want to include
skills:
 - Java
 - Python
 - Selenium
 - Appium
 - SQL
 - QTP
 - Katalon

#Blogfeed is optional - including this will add JS to call the feed and populate blog list
blogfeed: http://armatethetechmate.blogspot.com/feeds/posts/default?alt=rss

#Work experience is required
roles:
 - title: Senior QA Engineer
   start: 2016
   end: Ongoing
   employer: Photon Infotech
   description: Photon is the worldâ€™s largest and fastest growing provider of omnichannel and digital experiences. Photon works with over 37% of the Fortune 100 as their digital innovation partner of choice and has the largest digital consumer footprint with over 250mn daily consumer touchpoints. Photon has the largest pool of omnichannel engineers with over 3,800 engineers across offices in the US, Canada, Europe, Mauritius, India, Shanghai, and Indonesia.
 - title: Senior Software Testing Engineer
   start: 2013
   end: 2016
   employer: IBS Software Services
   description: IBS is a leading global provider of new generation IT solutions to the Travel, Transportation and Logistics industries. A specialist in the domain, IBS offers a range of products and services that manage mission critical operations of airlines, airports, cruise lines, hospitality partners, tour operators and oil & gas companies that help them increase safety, maximize efficiency, improve revenue, manage growth and reduce costs.
 - title: Software Testing Engineer - 2.
   start: 2011
   end: 2013
   employer: Sobha Developers Ltd
   description: A range of functional and technical roles, primarily working on client sites in Financial Services.

#Education is required
education:
 - level: Bachelor of Engineering
   date: 2010
   subject: Computer Science
   school: Visvesvaraya Technological University

#This section is optional (as is the image link below)
coursera:
   profileurl: https://www.coursera.org/user/4e2b22947bf1b1fdff4f6cdf952146a3
   courses:
    - title: CODAPPS-Coding mobile apps for entrepreneurs
      link: https://www.coursera.org/learn/codapps/home/welcome
      date: Nov 15 2016

#List of interesting Github repo/projects to include - optional
github:
 - arjunbm13/awesome-test-automation
 - arjunbm13/testingconferences.github.io
 - arjunbm13/awesome-appium
 - arjunbm13/awesome-java
 - arjunbm13/List_Of_Free_MOOC
 - arjunbm13/awesome-github
 - arjunbm13/awesome
 - arjunbm13/awesome-selenium
 - arjunbm13/awesome-courses
 - arjunbm13/awesome-bitcoin
 - arjunbm13/MOOC
 - arjunbm13/javaForTestersCode
 - arjunbm13/free-software-testing-books

#Stackoverflow flair is optional
stackoverflow:
   profileurl: https://stackoverflow.com/users/3282775/armate
   flairimageurl: https://stackoverflow.com/users/flair/3282775.png

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
   Over <strong>7+</strong> years of testing experience in ERP, Web, Service and Mobile Applications with deep understanding of <strong>Manual</strong> and <strong>Automation testing Experience</strong>.
   Are you a software company or a QA person or a  tester who wants to get on the test automation path, but don't know where to start?
   Are you already on the path and stuck somewhere or started new?
   Are you having problems getting quality product delivered to your customers or clients?
   I help teams and companies reach their full potential by coming alongside, and teaching them what common automation pitfalls to avoid, and how to future-proof their infrastructure and help them optimize.
   <br/><br/>
   I am a tech-savvy guy from Bangalore, India. Passionate about all technologies, not just coding. I like to spend my time thinking and working on interesting ideas, meeting interesting people and contributing to projects I care about.
   I am proficient Java, Python but more importantly, I am a fast learner who thinks about the big picture.So if you want to talk or ask me anything, and I'll do my best to answer.
   <strong>If I can't, I will try to connect to someone who can help. If I don't, you don't pay!</strong>

theme: jekyll-theme-cayman