# Site settings
title: Alex Solntsev
twitter_username: lejbron
name: Alex Solntsev

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: Arduino Blog
   url: https://create.arduino.cc/projecthub/lejbron
 - title: GitHub
   url: https://github.com/lejbron

#Any buzzword skills you want to include
skills:
 - reStructuredText
 - Sphinx
 - Jenkins
 - Docker
 - C++
 
#Blogfeed is optional - including this will add JS to call the feed and populate blog list
#blogfeed: https://automateddeveloper.blogspot.com/feeds/posts/default?alt=json

#Work experience is required
roles:
 - title: Technical Writer
   start: 2018
   end: Ongoing
   employer: Mail.ru Group
   description: 
    - collect information about key featers of existing classified service;
    - create detailed description of current processes in .rst format; 
    - build static site with product documentation from .rst files;
    - administrate host with documentation site in local subnet of development team;
 - title: Senior Engineer
   start: 2016
   end: 2018
   employer: FORS Distribution Center
   description: 
    - created user manuals for custoimized product version of Oracle Identity Management at implementation project in bank;
    - wrote detailed manual for administrators about installation of OIM customizations.
 
#Education is required
education:
 - level: Specialist
   date: 2014
   subject: Applied informatics in economics
   school: Plekhanov Russioan University of Economics

#This section is optional (as is the image link below)
#coursera:
#   profileurl: https://www.coursera.org/user/i/c6362b4056f755a04bef6a791a62102b
#   courses:
#    - title: Functional Programming Principles in Scala
#      link: https://www.coursera.org/course/progfun
#      optionalimage: https://d1z850dzhxs7de.cloudfront.net/topics/progfun/small-icon.hover.png
#      date: September 16, 2013
#    - title: Algorithms Design and Analysis, Part 1
#      link: https://www.coursera.org/specializations/algorithms
#      optionalimage: https://d1z850dzhxs7de.cloudfront.net/topics/algo/small-icon.hover.png
#      date: April 28, 2014

#List of interesting Github repo/projects to include - optional
github:
 - lejbron/lejbron.github.io
 - lejbron/IskraNeoProjects
 

#Stackoverflow flair is optional
#stackoverflow:
#   profileurl: http://stackoverflow.com/users/258813/rhinds
#   flairimageurl: http://stackoverflow.com/users/flair/258813.png

intro: |
  in progress
  
#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
   no
