# Site settings
title: Jonas Miosga
name: Jonas Miosga

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: GitHub
   url: https://github.com/miosga2309
 - title: LinkedIn
   url: https://www.linkedin.com/in/jonas-miosga/

#Any buzzword skills you want to include
skills:
 - Python
 - R
 - Multilevel Modeling
 - Flask
 - SAS/SPSS/MatLab/Java
 - API design
 - SQL
 - Machine learning

#Work experience is required
roles:
 - title: ...
   start: 2017
   end: ...
   employer: ...
   description: ...

#Education is required
education:
-  level: Master of Science (M.Sc.)
   date: ongoing
   subject: Data Science
   school: University of Konstanz
 - level: Bachelor of Science (B.Sc.)
   date: 2018
   subject: Psychology
   school: University of Groningen

#This section is optional (as is the image link below)
Udemy:
   profileurl: https://www.udemy.com/user/jonas-miosga/
   courses:
    - title: The Python Mega Course: Build 10 Real World Applications
      link: https://www.udemy.com/the-python-mega-course/
      date: September 16, 2019


#List of interesting Github repo/projects to include - optional
github:
 - miosga2309/miosga2309.github.io


intro: |
...

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
   ...
