# Site settings
title: Eduardo Cordova
twitter_username: eduardoawakens
name: Eduardo Alfredo Cordova Mancheno

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
# - title: Blog
#   url: https://automateddeveloper.blogspot.com/
 - title: GitHub
   url: https://github.com/eduardocordova
# - title: StackOverflow
#   url: https://stackoverflow.com/users/9956291/edc
# - title: DZone
#   url: https://dzone.com/users/899489/rhinds.html
 - title: LinkedIn
   url: https://www.linkedin.com/in/eduardo-cordova-mancheno/
# - title: Food
#   url: https://www.robbishfood.com/

#Any buzzword skills you want to include
skills:
 - Java
 - Python
 - Machine Learning
 - NLP
 - Text summarization
 - Web
 - Mobile
 - RPA
 - Design


#Blogfeed is optional - including this will add JS to call the feed and populate blog list
#blogfeed: https://automateddeveloper.blogspot.com/feeds/posts/default?alt=json

#Work experience is required
roles:
 - title: Analyst / Programmer
   start: 2019
   end: 2021
   employer: Maint S.A.
   description: Obtained certifications in RPA (UIPath, Automation Anywhere) and Analytics (Vertica).
 - title: Consultant
   start: 2015
   end: 2016
   employer: Industria Solex
   description: Collection, analysis, interpretation, presentation, and organization of data.
 - title: Junior Designer and Developer
   start: 2013
   end: 2014
   employer: Crifa Cia. Ltda.
   description: Web design, Web Development. Obtained Zend PHP certification
 - title: Coordinator
   start: 2010
   end: 2013
   employer: Guayaquil Construction Chamber
   description: Responsible for digital identity, audiovisual assignments, webmaster, social networks management and organization of events.
 - title: Post-Producer
   start: 2010
   end: 2010
   employer: Canal Uno
   description:Motion Graphics, 3D animations , TV Shows Promos.
 - title: Casting Director / Editor
   start: 2009
   end: 2010
   employer: Canal Uno
   description:Responsible for the technical area, castings, edit and post-production of TV spots.
 - title: Editor
   start: 2008
   end: 2009
   employer: Xtreme Film Production
   description:Responsible for video edition and post production of TV program "Casa y Diseño", International Ecuavisa.

#Education is required
education:
 - level: Master of Science (M.Sc.)
   date: 2018
   subject: Computer Science and Engineering
   school: Politecnico di Milano

#This section is optional (as is the image link below)
#coursera:
#   profileurl: https://www.coursera.org/user/i/c6362b4056f755a04bef6a791a62102b
#   courses:
#    - title: Functional Programming Principles in Scala
#      link: https://www.coursera.org/course/progfun
#      optionalimage: https://d1z850dzhxs7de.cloudfront.net/topics/progfun/small-icon.hover.png
#      date: September 16, 2013
#    - title: Algorithms Design and Analysis, Part 1
#      link: https://www.coursera.org/specializations/algorithms
#      optionalimage: https://d1z850dzhxs7de.cloudfront.net/topics/algo/small-icon.hover.png
#      date: April 28, 2014

#This section is optional - embeds slideshows from speakerdeck
# to get the speakerdeck ID copy the embed code and look for the data-it attribute
#speakerdeck:
#   profileurl: https://speakerdeck.com/robhinds
#   talks:
#    - title: Product Management for Engineers
#      speakerdeckId: 94f0070c4e434ec79fe9b4eb2cb574e0
#      conference: API Conference, Berlin 2018
#    - title: Agile Machine Learning - from Theory to Production
#      speakerdeckId: ec84f2f56e9743afb0675b1eeeb6b6ce
#      conference: W-JAX Conference, Munich 2017 (London 2017)

#List of interesting Github repo/projects to include - optional
#github:
# - robhinds/robhinds.github.io
# - robhinds/ScaLambda
# - robhinds/opinionated-akka-http
# - robhinds/food2vec
# - robhinds/microservices
# - robhinds/spring-social-geeklist
# - robhinds/spring-social-stackoverflow
# - robhinds/genotype
# - robhinds/footweets
# - robhinds/ElasticSearchGradle

#Stackoverflow flair is optional
#stackoverflow:
#   profileurl: https://stackoverflow.com/users/258813/rhinds
#   flairimageurl: https://stackoverflow.com/users/flair/258813.png

intro: |
  I’m a person closely related to new technologies and deep learning with an interest in NLP.<br/><br/>
  I've recently worked in RPA and CRM projects.<br/><br/>
  Before that I worked in different industries, gathering experience in many disciplines like multimedia, web development, video and design.<br/><br/>

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
#additionalinfo: |
#   <strong>Scala</strong>: My current role uses Scala as the primary language and have been building applications in Scala for the last two years. I am familiar with a range of Scala libraries, such as <a target="_blank" href="https://automateddeveloper.blogspot.com/2017/12/an-opinionated-guide-to-building-apis.html"> Akka-Http for building microservices</a> and <a target="_blank" href="https://automateddeveloper.blogspot.com/2018/09/generic-programming-with-scala.html"> Shapeless for generic programming</a>, as well as familiar with a range of <a target="_blank" href="https://basementcrowd.com/2018/11/28/scala-the-aux-pattern-path-dependent-types/" >functional programming techniques available</a>.<br/><br/>
#   <strong>Java</strong>: I am experienced in a variety of Java API’s and frameworks. I have worked with Spring 4, Spring Boot, JPA (Hibernate and EclipseLink) in addition to others. <br/><br/>
#   <strong>Groovy</strong> I have used Groovy as a language in production for ~4 years and I am familiar with many of the languages features (such as writing <a target='_blank' href="https://dzone.com/articles/functional-programming-groovy">Functional Programming style groovy</a>) and quirks (such as <a target="_blank" href="https://dzone.com/articles/groovy-retrospective-an-addendum-memory-usage-perm">memory leak issues</a>). <br/><br/>
#   <strong>Cloud platforms</strong>: I have primarily used AWS for running production apps on the cloud. I have experience setting up, configuring and running applications using a range of AWS offerings, including EC2, RDS, S3, Cogito, <a target="_blank" href="https://automateddeveloper.blogspot.com/2018/05/serverless-with-aws-lambda-scala.html">Lambda</a> and its more recent <a target="_blank" href="https://automateddeveloper.blogspot.com/2018/10/machine-learning-with-aws-scala.html">Machine Learning capabilities</a>.<br/><br/>
#   <strong>Web Development</strong>: Through building web applications, I have also worked with various client side technology, having used jQuery, Bootstrap, LESS, SASS, Backbone/Underscore/Require. More recently I have written React applications (primarily using the Create React App framework, and extending them)<br/><br/>
#   <strong>Development Control</strong>: I have a good knowledge of application life-cycle management and have worked with SVN, Git, Maven, Gradle, Sonar, Jenkins, TeamCity, etc. I have experience with an array of testing tools and technologies.<br/><br/>
#   I have also gained experience and knowledge of other technologies from several side projects and research that I have undertaken in my free time, including Android, a variety of social APIs (Twitter etc) and cloud platforms such as CloudFoundry/OpenShift/AppFog/AWS. <br/><br/>
#   As part of Nerdability, I created, and am now primary contributor to, two Spring projects - <a target='_blank' href="https://github.com/robhinds/spring-social-geeklist">Spring-Social-Geeklist</a> and <a target='_blank' href="https://github.com/nerdability/spring-social-khan-academy">Spring-Social-Khan-Academy</a>, which provide core integration with those third-party APIs on top of the Spring Social framework. They are both listed as community projects: <a target='_blank' href="https://projects.spring.io/spring-social/">https://projects.spring.io/spring-social/</a>. <br/><br/>
#   I write a blog covering technical and opinion articles that can be found here: <a target='_blank' href="https://automateddeveloper.blogspot.com/">automateddeveloper.blogspot.com</a> (I am also a <a target='_blank' href="https://dzone.com/users/899489/rhinds.html">DZone MVB</a>)
